### ISSUE TITLE
Implementar la autentificación de Empresa

### ISSUE THREAD

**Issue by omiras** [Formate-con-Altia/valida.me#12]
# Objetivo y análisis

Una empresa debe poderse registrar para ver/gestionar sus formularios

## Implementar registro y login

1. Adaptar el proyecto en  https://github.com/Formate-con-Altia/valida.me/issues/6 ; para crear una pantalla de login/registro (figma). Usar los campos mínimos, como los que aparecen en el proyecto. Sugiero usar solo nombre de empresa, además de email y contraseña.
2. Sugiero intentar primero autentificación solo por usuario/contraseña
3. Crear una ruta como en proyecto tipo /profile, que solo un usuario autentificado pueda acceder, y que simplemente muestra información básico del usuario:;
![image](https://user-images.githubusercontent.com/3286458/152120791-e3c42234-7a83-43d1-a7e7-097390a652f1.png)
4. Para hacer este /profile, echad un vistazo a https://github.com/FOAP-Netmind-2021/avisa-me/blob/main/views/user/profile.ejs o al mismo profile.ejs del proyecto passport-auth-nodejs https://github.com/bdcorps/passport-auth-nodejs/blob/main/views/profile.ejs
5. Crear un login.ejs tanto para signup y login. O si queréis, ponerlo en ficheros diferentes: signup.ejs, login.ejs https://www.figma.com/file/so4zBEOdRV7JkNRWhmJl21/Validame?node-id=51%3A45
6. Crear profile.ejs muy básica.

**Comment by arlomba** [comment]
# Cambios recientes
- Añadido el modelo de usuario.
- Implementado el login, logout y registro de un usuario
- Implementado middleware para saber si estás autenticado o no, de esta forma podremos proteger las rutas
- Identificación del metodo de registro del usuario (`google` o `local`).
- Implementada la encriptación de contraseñas 
- Refactor del código.
