### ISSUE TITLE
Crear GMAIL corporativo y alta en MongoDB Atlas

### ISSUE THREAD

**Issue by omiras** [Formate-con-Altia/valida.me#5]
1. Crear gmail corporativo **validameapp@gmail.com**
2. Alta en MongoDB Atlas
3. Compartir los datos de conexión con los compañero/as en Discord en #proyecto-final

**Comment by omiras** [comment]
He puesto mi telefono en personal en Gmail

**Comment by Aap138** [comment]
validameapp ya esta dado de alta en gmail, mongodb uri y mongodb atlas, se ha puesto la direccion de correo y contraseña en discord

**Comment by omiras** [comment]
En el mismo canal de discord tenemos publicadas ya las API Keys de Google (Passport)
